//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xuly
{
    using System;
    using System.Collections.Generic;
    
    public partial class doibong
    {
        public int idtendoibong { get; set; }
        public string tendoibong { get; set; }
    }
}
