//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xuly
{
    using System;
    using System.Collections.Generic;
    
    public partial class quanlyTK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public quanlyTK()
        {
            this.thongtinchung = new HashSet<thongtinchung>();
        }
    
        public int idTK { get; set; }
        public string SoTK { get; set; }
        public string TenTkDayDU { get; set; }
        public string TenTk { get; set; }
        public string NguoiCaDoCung { get; set; }
        public string TenNguoiCaDoCung { get; set; }
        public Nullable<decimal> GiaUSDTK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thongtinchung> thongtinchung { get; set; }
    }
}
