#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExcel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="cobac2")]
	public partial class CadoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcachthuccado(cachthuccado instance);
    partial void Updatecachthuccado(cachthuccado instance);
    partial void Deletecachthuccado(cachthuccado instance);
    partial void Insertthongtinchung(thongtinchung instance);
    partial void Updatethongtinchung(thongtinchung instance);
    partial void Deletethongtinchung(thongtinchung instance);
    partial void Insertdoibong(doibong instance);
    partial void Updatedoibong(doibong instance);
    partial void Deletedoibong(doibong instance);
    partial void Insertgiaidau(giaidau instance);
    partial void Updategiaidau(giaidau instance);
    partial void Deletegiaidau(giaidau instance);
    partial void InsertquanlyTK(quanlyTK instance);
    partial void UpdatequanlyTK(quanlyTK instance);
    partial void DeletequanlyTK(quanlyTK instance);
    #endregion
		
		public CadoDataContext() : 
				base(global::ImportExcel.Properties.Settings.Default.cobac2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CadoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CadoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CadoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CadoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cachthuccado> cachthuccados
		{
			get
			{
				return this.GetTable<cachthuccado>();
			}
		}
		
		public System.Data.Linq.Table<thongtinchung> thongtinchungs
		{
			get
			{
				return this.GetTable<thongtinchung>();
			}
		}
		
		public System.Data.Linq.Table<doibong> doibongs
		{
			get
			{
				return this.GetTable<doibong>();
			}
		}
		
		public System.Data.Linq.Table<giaidau> giaidaus
		{
			get
			{
				return this.GetTable<giaidau>();
			}
		}
		
		public System.Data.Linq.Table<quanlyTK> quanlyTKs
		{
			get
			{
				return this.GetTable<quanlyTK>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cachthuccado")]
	public partial class cachthuccado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idcachthuccado;
		
		private string _tencachthuccado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidcachthuccadoChanging(int value);
    partial void OnidcachthuccadoChanged();
    partial void OntencachthuccadoChanging(string value);
    partial void OntencachthuccadoChanged();
    #endregion
		
		public cachthuccado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcachthuccado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idcachthuccado
		{
			get
			{
				return this._idcachthuccado;
			}
			set
			{
				if ((this._idcachthuccado != value))
				{
					this.OnidcachthuccadoChanging(value);
					this.SendPropertyChanging();
					this._idcachthuccado = value;
					this.SendPropertyChanged("idcachthuccado");
					this.OnidcachthuccadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tencachthuccado", DbType="NVarChar(50)")]
		public string tencachthuccado
		{
			get
			{
				return this._tencachthuccado;
			}
			set
			{
				if ((this._tencachthuccado != value))
				{
					this.OntencachthuccadoChanging(value);
					this.SendPropertyChanging();
					this._tencachthuccado = value;
					this.SendPropertyChanged("tencachthuccado");
					this.OntencachthuccadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.thongtinchung")]
	public partial class thongtinchung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idthongtin;
		
		private int _id_quanlyTK_idTK;
		
		private System.DateTime _thoigiancado;
		
		private System.TimeSpan _gio;
		
		private System.DateTime _ngay;
		
		private string _cuacado;
		
		private string _cachthuccado;
		
		private string _tylechap;
		
		private string _hinhthuccado;
		
		private string _doibong1;
		
		private string _doibong2;
		
		private string _tengiaidau;
		
		private string _giaidaumorong;
		
		private string _tylecuoc;
		
		private System.Nullable<decimal> _tiencuoc;
		
		private System.Nullable<decimal> _tienthang_thua;
		
		private System.Nullable<decimal> _ketqua_trongkeo;
		
		private System.Nullable<decimal> _com;
		
		private string _trangthai;
		
		private string _hiepcado;
		
		private System.Nullable<int> _weekofyear;
		
		private EntityRef<quanlyTK> _quanlyTK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidthongtinChanging(int value);
    partial void OnidthongtinChanged();
    partial void Onid_quanlyTK_idTKChanging(int value);
    partial void Onid_quanlyTK_idTKChanged();
    partial void OnthoigiancadoChanging(System.DateTime value);
    partial void OnthoigiancadoChanged();
    partial void OngioChanging(System.TimeSpan value);
    partial void OngioChanged();
    partial void OnngayChanging(System.DateTime value);
    partial void OnngayChanged();
    partial void OncuacadoChanging(string value);
    partial void OncuacadoChanged();
    partial void OncachthuccadoChanging(string value);
    partial void OncachthuccadoChanged();
    partial void OntylechapChanging(string value);
    partial void OntylechapChanged();
    partial void OnhinhthuccadoChanging(string value);
    partial void OnhinhthuccadoChanged();
    partial void Ondoibong1Changing(string value);
    partial void Ondoibong1Changed();
    partial void Ondoibong2Changing(string value);
    partial void Ondoibong2Changed();
    partial void OntengiaidauChanging(string value);
    partial void OntengiaidauChanged();
    partial void OngiaidaumorongChanging(string value);
    partial void OngiaidaumorongChanged();
    partial void OntylecuocChanging(string value);
    partial void OntylecuocChanged();
    partial void OntiencuocChanging(System.Nullable<decimal> value);
    partial void OntiencuocChanged();
    partial void Ontienthang_thuaChanging(System.Nullable<decimal> value);
    partial void Ontienthang_thuaChanged();
    partial void Onketqua_trongkeoChanging(System.Nullable<decimal> value);
    partial void Onketqua_trongkeoChanged();
    partial void OncomChanging(System.Nullable<decimal> value);
    partial void OncomChanged();
    partial void OntrangthaiChanging(string value);
    partial void OntrangthaiChanged();
    partial void OnhiepcadoChanging(string value);
    partial void OnhiepcadoChanged();
    partial void OnweekofyearChanging(System.Nullable<int> value);
    partial void OnweekofyearChanged();
    #endregion
		
		public thongtinchung()
		{
			this._quanlyTK = default(EntityRef<quanlyTK>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idthongtin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idthongtin
		{
			get
			{
				return this._idthongtin;
			}
			set
			{
				if ((this._idthongtin != value))
				{
					this.OnidthongtinChanging(value);
					this.SendPropertyChanging();
					this._idthongtin = value;
					this.SendPropertyChanged("idthongtin");
					this.OnidthongtinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_quanlyTK_idTK", DbType="Int NOT NULL")]
		public int id_quanlyTK_idTK
		{
			get
			{
				return this._id_quanlyTK_idTK;
			}
			set
			{
				if ((this._id_quanlyTK_idTK != value))
				{
					if (this._quanlyTK.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_quanlyTK_idTKChanging(value);
					this.SendPropertyChanging();
					this._id_quanlyTK_idTK = value;
					this.SendPropertyChanged("id_quanlyTK_idTK");
					this.Onid_quanlyTK_idTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigiancado", DbType="DateTime NOT NULL")]
		public System.DateTime thoigiancado
		{
			get
			{
				return this._thoigiancado;
			}
			set
			{
				if ((this._thoigiancado != value))
				{
					this.OnthoigiancadoChanging(value);
					this.SendPropertyChanging();
					this._thoigiancado = value;
					this.SendPropertyChanged("thoigiancado");
					this.OnthoigiancadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gio", DbType="Time NOT NULL")]
		public System.TimeSpan gio
		{
			get
			{
				return this._gio;
			}
			set
			{
				if ((this._gio != value))
				{
					this.OngioChanging(value);
					this.SendPropertyChanging();
					this._gio = value;
					this.SendPropertyChanged("gio");
					this.OngioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay", DbType="Date NOT NULL")]
		public System.DateTime ngay
		{
			get
			{
				return this._ngay;
			}
			set
			{
				if ((this._ngay != value))
				{
					this.OnngayChanging(value);
					this.SendPropertyChanging();
					this._ngay = value;
					this.SendPropertyChanged("ngay");
					this.OnngayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuacado", DbType="NVarChar(50)")]
		public string cuacado
		{
			get
			{
				return this._cuacado;
			}
			set
			{
				if ((this._cuacado != value))
				{
					this.OncuacadoChanging(value);
					this.SendPropertyChanging();
					this._cuacado = value;
					this.SendPropertyChanged("cuacado");
					this.OncuacadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cachthuccado", DbType="NVarChar(50)")]
		public string cachthuccado
		{
			get
			{
				return this._cachthuccado;
			}
			set
			{
				if ((this._cachthuccado != value))
				{
					this.OncachthuccadoChanging(value);
					this.SendPropertyChanging();
					this._cachthuccado = value;
					this.SendPropertyChanged("cachthuccado");
					this.OncachthuccadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tylechap", DbType="NVarChar(50)")]
		public string tylechap
		{
			get
			{
				return this._tylechap;
			}
			set
			{
				if ((this._tylechap != value))
				{
					this.OntylechapChanging(value);
					this.SendPropertyChanging();
					this._tylechap = value;
					this.SendPropertyChanged("tylechap");
					this.OntylechapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhthuccado", DbType="NVarChar(50)")]
		public string hinhthuccado
		{
			get
			{
				return this._hinhthuccado;
			}
			set
			{
				if ((this._hinhthuccado != value))
				{
					this.OnhinhthuccadoChanging(value);
					this.SendPropertyChanging();
					this._hinhthuccado = value;
					this.SendPropertyChanged("hinhthuccado");
					this.OnhinhthuccadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doibong1", DbType="NVarChar(100)")]
		public string doibong1
		{
			get
			{
				return this._doibong1;
			}
			set
			{
				if ((this._doibong1 != value))
				{
					this.Ondoibong1Changing(value);
					this.SendPropertyChanging();
					this._doibong1 = value;
					this.SendPropertyChanged("doibong1");
					this.Ondoibong1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doibong2", DbType="NVarChar(100)")]
		public string doibong2
		{
			get
			{
				return this._doibong2;
			}
			set
			{
				if ((this._doibong2 != value))
				{
					this.Ondoibong2Changing(value);
					this.SendPropertyChanging();
					this._doibong2 = value;
					this.SendPropertyChanged("doibong2");
					this.Ondoibong2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tengiaidau", DbType="NVarChar(MAX)")]
		public string tengiaidau
		{
			get
			{
				return this._tengiaidau;
			}
			set
			{
				if ((this._tengiaidau != value))
				{
					this.OntengiaidauChanging(value);
					this.SendPropertyChanging();
					this._tengiaidau = value;
					this.SendPropertyChanged("tengiaidau");
					this.OntengiaidauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaidaumorong", DbType="NVarChar(MAX)")]
		public string giaidaumorong
		{
			get
			{
				return this._giaidaumorong;
			}
			set
			{
				if ((this._giaidaumorong != value))
				{
					this.OngiaidaumorongChanging(value);
					this.SendPropertyChanging();
					this._giaidaumorong = value;
					this.SendPropertyChanged("giaidaumorong");
					this.OngiaidaumorongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tylecuoc", DbType="NVarChar(50)")]
		public string tylecuoc
		{
			get
			{
				return this._tylecuoc;
			}
			set
			{
				if ((this._tylecuoc != value))
				{
					this.OntylecuocChanging(value);
					this.SendPropertyChanging();
					this._tylecuoc = value;
					this.SendPropertyChanged("tylecuoc");
					this.OntylecuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiencuoc", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> tiencuoc
		{
			get
			{
				return this._tiencuoc;
			}
			set
			{
				if ((this._tiencuoc != value))
				{
					this.OntiencuocChanging(value);
					this.SendPropertyChanging();
					this._tiencuoc = value;
					this.SendPropertyChanged("tiencuoc");
					this.OntiencuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tienthang_thua", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> tienthang_thua
		{
			get
			{
				return this._tienthang_thua;
			}
			set
			{
				if ((this._tienthang_thua != value))
				{
					this.Ontienthang_thuaChanging(value);
					this.SendPropertyChanging();
					this._tienthang_thua = value;
					this.SendPropertyChanged("tienthang_thua");
					this.Ontienthang_thuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ketqua_trongkeo", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ketqua_trongkeo
		{
			get
			{
				return this._ketqua_trongkeo;
			}
			set
			{
				if ((this._ketqua_trongkeo != value))
				{
					this.Onketqua_trongkeoChanging(value);
					this.SendPropertyChanging();
					this._ketqua_trongkeo = value;
					this.SendPropertyChanged("ketqua_trongkeo");
					this.Onketqua_trongkeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> com
		{
			get
			{
				return this._com;
			}
			set
			{
				if ((this._com != value))
				{
					this.OncomChanging(value);
					this.SendPropertyChanging();
					this._com = value;
					this.SendPropertyChanged("com");
					this.OncomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="NVarChar(10)")]
		public string trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hiepcado", DbType="NVarChar(10)")]
		public string hiepcado
		{
			get
			{
				return this._hiepcado;
			}
			set
			{
				if ((this._hiepcado != value))
				{
					this.OnhiepcadoChanging(value);
					this.SendPropertyChanging();
					this._hiepcado = value;
					this.SendPropertyChanged("hiepcado");
					this.OnhiepcadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weekofyear", DbType="Int")]
		public System.Nullable<int> weekofyear
		{
			get
			{
				return this._weekofyear;
			}
			set
			{
				if ((this._weekofyear != value))
				{
					this.OnweekofyearChanging(value);
					this.SendPropertyChanging();
					this._weekofyear = value;
					this.SendPropertyChanged("weekofyear");
					this.OnweekofyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="quanlyTK_thongtinchung", Storage="_quanlyTK", ThisKey="id_quanlyTK_idTK", OtherKey="idTK", IsForeignKey=true)]
		public quanlyTK quanlyTK
		{
			get
			{
				return this._quanlyTK.Entity;
			}
			set
			{
				quanlyTK previousValue = this._quanlyTK.Entity;
				if (((previousValue != value) 
							|| (this._quanlyTK.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._quanlyTK.Entity = null;
						previousValue.thongtinchungs.Remove(this);
					}
					this._quanlyTK.Entity = value;
					if ((value != null))
					{
						value.thongtinchungs.Add(this);
						this._id_quanlyTK_idTK = value.idTK;
					}
					else
					{
						this._id_quanlyTK_idTK = default(int);
					}
					this.SendPropertyChanged("quanlyTK");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.doibong")]
	public partial class doibong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idtendoibong;
		
		private string _tendoibong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidtendoibongChanging(int value);
    partial void OnidtendoibongChanged();
    partial void OntendoibongChanging(string value);
    partial void OntendoibongChanged();
    #endregion
		
		public doibong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idtendoibong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idtendoibong
		{
			get
			{
				return this._idtendoibong;
			}
			set
			{
				if ((this._idtendoibong != value))
				{
					this.OnidtendoibongChanging(value);
					this.SendPropertyChanging();
					this._idtendoibong = value;
					this.SendPropertyChanged("idtendoibong");
					this.OnidtendoibongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendoibong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tendoibong
		{
			get
			{
				return this._tendoibong;
			}
			set
			{
				if ((this._tendoibong != value))
				{
					this.OntendoibongChanging(value);
					this.SendPropertyChanging();
					this._tendoibong = value;
					this.SendPropertyChanged("tendoibong");
					this.OntendoibongChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.giaidau")]
	public partial class giaidau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idgiadau;
		
		private string _tengiaidau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidgiadauChanging(int value);
    partial void OnidgiadauChanged();
    partial void OntengiaidauChanging(string value);
    partial void OntengiaidauChanged();
    #endregion
		
		public giaidau()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idgiadau", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idgiadau
		{
			get
			{
				return this._idgiadau;
			}
			set
			{
				if ((this._idgiadau != value))
				{
					this.OnidgiadauChanging(value);
					this.SendPropertyChanging();
					this._idgiadau = value;
					this.SendPropertyChanged("idgiadau");
					this.OnidgiadauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tengiaidau", DbType="NVarChar(MAX)")]
		public string tengiaidau
		{
			get
			{
				return this._tengiaidau;
			}
			set
			{
				if ((this._tengiaidau != value))
				{
					this.OntengiaidauChanging(value);
					this.SendPropertyChanging();
					this._tengiaidau = value;
					this.SendPropertyChanged("tengiaidau");
					this.OntengiaidauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.quanlyTK")]
	public partial class quanlyTK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTK;
		
		private string _SoTK;
		
		private string _TenTkDayDU;
		
		private string _TenTk;
		
		private string _NguoiCaDoCung;
		
		private string _TenNguoiCaDoCung;
		
		private System.Nullable<decimal> _GiaUSDTK;
		
		private EntitySet<thongtinchung> _thongtinchungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTKChanging(int value);
    partial void OnidTKChanged();
    partial void OnSoTKChanging(string value);
    partial void OnSoTKChanged();
    partial void OnTenTkDayDUChanging(string value);
    partial void OnTenTkDayDUChanged();
    partial void OnTenTkChanging(string value);
    partial void OnTenTkChanged();
    partial void OnNguoiCaDoCungChanging(string value);
    partial void OnNguoiCaDoCungChanged();
    partial void OnTenNguoiCaDoCungChanging(string value);
    partial void OnTenNguoiCaDoCungChanged();
    partial void OnGiaUSDTKChanging(System.Nullable<decimal> value);
    partial void OnGiaUSDTKChanged();
    #endregion
		
		public quanlyTK()
		{
			this._thongtinchungs = new EntitySet<thongtinchung>(new Action<thongtinchung>(this.attach_thongtinchungs), new Action<thongtinchung>(this.detach_thongtinchungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTK
		{
			get
			{
				return this._idTK;
			}
			set
			{
				if ((this._idTK != value))
				{
					this.OnidTKChanging(value);
					this.SendPropertyChanging();
					this._idTK = value;
					this.SendPropertyChanged("idTK");
					this.OnidTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTK", DbType="NVarChar(20)")]
		public string SoTK
		{
			get
			{
				return this._SoTK;
			}
			set
			{
				if ((this._SoTK != value))
				{
					this.OnSoTKChanging(value);
					this.SendPropertyChanging();
					this._SoTK = value;
					this.SendPropertyChanged("SoTK");
					this.OnSoTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTkDayDU", DbType="NVarChar(25)")]
		public string TenTkDayDU
		{
			get
			{
				return this._TenTkDayDU;
			}
			set
			{
				if ((this._TenTkDayDU != value))
				{
					this.OnTenTkDayDUChanging(value);
					this.SendPropertyChanging();
					this._TenTkDayDU = value;
					this.SendPropertyChanged("TenTkDayDU");
					this.OnTenTkDayDUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTk", DbType="NVarChar(10)")]
		public string TenTk
		{
			get
			{
				return this._TenTk;
			}
			set
			{
				if ((this._TenTk != value))
				{
					this.OnTenTkChanging(value);
					this.SendPropertyChanging();
					this._TenTk = value;
					this.SendPropertyChanged("TenTk");
					this.OnTenTkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCaDoCung", DbType="NVarChar(50)")]
		public string NguoiCaDoCung
		{
			get
			{
				return this._NguoiCaDoCung;
			}
			set
			{
				if ((this._NguoiCaDoCung != value))
				{
					this.OnNguoiCaDoCungChanging(value);
					this.SendPropertyChanging();
					this._NguoiCaDoCung = value;
					this.SendPropertyChanged("NguoiCaDoCung");
					this.OnNguoiCaDoCungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiCaDoCung", DbType="NVarChar(50)")]
		public string TenNguoiCaDoCung
		{
			get
			{
				return this._TenNguoiCaDoCung;
			}
			set
			{
				if ((this._TenNguoiCaDoCung != value))
				{
					this.OnTenNguoiCaDoCungChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiCaDoCung = value;
					this.SendPropertyChanged("TenNguoiCaDoCung");
					this.OnTenNguoiCaDoCungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaUSDTK", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> GiaUSDTK
		{
			get
			{
				return this._GiaUSDTK;
			}
			set
			{
				if ((this._GiaUSDTK != value))
				{
					this.OnGiaUSDTKChanging(value);
					this.SendPropertyChanging();
					this._GiaUSDTK = value;
					this.SendPropertyChanged("GiaUSDTK");
					this.OnGiaUSDTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="quanlyTK_thongtinchung", Storage="_thongtinchungs", ThisKey="idTK", OtherKey="id_quanlyTK_idTK")]
		public EntitySet<thongtinchung> thongtinchungs
		{
			get
			{
				return this._thongtinchungs;
			}
			set
			{
				this._thongtinchungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_thongtinchungs(thongtinchung entity)
		{
			this.SendPropertyChanging();
			entity.quanlyTK = this;
		}
		
		private void detach_thongtinchungs(thongtinchung entity)
		{
			this.SendPropertyChanging();
			entity.quanlyTK = null;
		}
	}
}
#pragma warning restore 1591
